### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by woodhull** [colorofchange/call-to-end-police-violence#1]
I really want someone to build a nice software-as-a-service "Call X and ask them to do Y" service with Twilio and a nice microsite builder. Initially targeting congress, but eventually everyone else in the world who could be a target. 

I talked to @debracleaver about this yesterday -- and then here's your new github repo with a promising name!

**Comment by jlev** [comment]
@woodhull, sorry I missed this. Working on rebuilding the call-congress tool to have a simple admin, so we can build these microsites more quickly. Right now it's all YAML files and manual setup with Twilio. Email me to chat further?
